services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    depends_on:
      - mongodb
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456789
      MONGO_INITDB_DATABASE: kit
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: