services:
  nginx:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - kit-network
      - shared-network
    container_name: kit_nginx

  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - kit-network
      - shared-network
    container_name: kit_app

networks:
  shared-network:
    name: "${BACKEND_NETWORK_NAME}"
    external: true
  kit-network:
    name: "kit-network"
    driver: bridge
